//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.16 at 09:42:04 AM IST 
//


package soap.card;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for creditCard complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="creditCard"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="cardNumber" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="cardCvv" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="cardExpiry" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="cardHolder" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="cardLimit" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="cardUsage" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="cardAvailable" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="cardStatus" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="cardPin" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "creditCard", propOrder = {
    "cardNumber",
    "cardCvv",
    "cardExpiry",
    "cardHolder",
    "cardLimit",
    "cardUsage",
    "cardAvailable",
    "cardStatus",
    "cardPin"
})
public class CreditCard {

    protected long cardNumber;
    protected int cardCvv;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar cardExpiry;
    @XmlElement(required = true)
    protected String cardHolder;
    protected int cardLimit;
    protected int cardUsage;
    protected int cardAvailable;
    protected boolean cardStatus;
    protected int cardPin;

    /**
     * Gets the value of the cardNumber property.
     * 
     */
    public long getCardNumber() {
        return cardNumber;
    }

    /**
     * Sets the value of the cardNumber property.
     * 
     */
    public void setCardNumber(long value) {
        this.cardNumber = value;
    }

    /**
     * Gets the value of the cardCvv property.
     * 
     */
    public int getCardCvv() {
        return cardCvv;
    }

    /**
     * Sets the value of the cardCvv property.
     * 
     */
    public void setCardCvv(int value) {
        this.cardCvv = value;
    }

    /**
     * Gets the value of the cardExpiry property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCardExpiry() {
        return cardExpiry;
    }

    /**
     * Sets the value of the cardExpiry property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCardExpiry(XMLGregorianCalendar value) {
        this.cardExpiry = value;
    }

    /**
     * Gets the value of the cardHolder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardHolder() {
        return cardHolder;
    }

    /**
     * Sets the value of the cardHolder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardHolder(String value) {
        this.cardHolder = value;
    }

    /**
     * Gets the value of the cardLimit property.
     * 
     */
    public int getCardLimit() {
        return cardLimit;
    }

    /**
     * Sets the value of the cardLimit property.
     * 
     */
    public void setCardLimit(int value) {
        this.cardLimit = value;
    }

    /**
     * Gets the value of the cardUsage property.
     * 
     */
    public int getCardUsage() {
        return cardUsage;
    }

    /**
     * Sets the value of the cardUsage property.
     * 
     */
    public void setCardUsage(int value) {
        this.cardUsage = value;
    }

    /**
     * Gets the value of the cardAvailable property.
     * 
     */
    public int getCardAvailable() {
        return cardAvailable;
    }

    /**
     * Sets the value of the cardAvailable property.
     * 
     */
    public void setCardAvailable(int value) {
        this.cardAvailable = value;
    }

    /**
     * Gets the value of the cardStatus property.
     * 
     */
    public boolean isCardStatus() {
        return cardStatus;
    }

    /**
     * Sets the value of the cardStatus property.
     * 
     */
    public void setCardStatus(boolean value) {
        this.cardStatus = value;
    }

    /**
     * Gets the value of the cardPin property.
     * 
     */
    public int getCardPin() {
        return cardPin;
    }

    /**
     * Sets the value of the cardPin property.
     * 
     */
    public void setCardPin(int value) {
        this.cardPin = value;
    }

}
